######################################################################
# Automatically generated by qmake (2.01a) Sat May 18 14:39:52 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += widget.h
FORMS += widget.ui
SOURCES += main.cpp widget.cpp
RESOURCES += qtMplayer.qrc
