######################################################################
# Automatically generated by qmake (2.01a) Mon Apr 22 12:29:36 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 1.cpp
