######################################################################
# Automatically generated by qmake (2.01a) Fri Apr 19 16:31:35 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += 1.cpp
