######################################################################
# Automatically generated by qmake (2.01a) Sat May 4 16:48:44 2013
######################################################################
QT       += core gui sql

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = world
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp
